### PR TITLE
Provide receiving  mail field in mailru provider.

### PR DESCRIPTION
**Pull request by dmitrymenshikov**
Hey!

Type: bug fix | new feature | code quality | documentation

Link to issue:

https://github.com/SocialConnect/auth/issues/134

- [x] I have read and understood the [Contributing Guidelines](https://github.com/SocialConnect/auth/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Small description of change:

Thanks :smiley_cat:

### CODE REVIEW

**Comment by ovr** [comment]
Can you please rebase this PR? Thanks

**Comment by dmitrymenshikov** [comment]
> Can you please rebase this PR? Thanks

Complete, check please.

**Comment by ADmad** [comment]
It's a bit weird that these providers decided to add the email to the "plain" OAuth2 token instead of switching over to OpenID Connect which provides a standardized way to include email and other claims in a JWT.

**Comment by ovr** [comment]
It's only about `Vk`,

@ADmad Probably they don't know about OpenID Connect :D

**Comment by ovr** [comment]
@dmitrymenshikov 

> Complete, check please.

You did a merge, not the rebase. Np, I cherry-pick a commit in `master`.

**Pull request closed without merging**
