### PR TITLE
Fixed Facebook provider exception when it is parsing token

### PR DESCRIPTION
**Pull request by pavellee**
Hey!

Type: bug fix
Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/SocialConnect/auth/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.

Small description of change:
Facebook provider generate exception when try parse token.
Thanks :smiley_cat:

### CODE REVIEW

**Comment by ovr** [comment]
AS I known, Facebook return token as string `access_token=XXXXX&expires=XXXX`
Why are you going to chage it to json? Thanks

**Comment by vitalybaev** [comment]
@ovr I've tried today on two projects and yes, Facebook not returns json

**Comment by ovr** [comment]
Okey, just give me a moment, I will take a look

**Comment by ovr** [comment]
Yep, it's rly broken, just give me ~10 minutes I will fix and release new version

**Comment by ovr** [comment]
Closed, because it's fixed in `master`
Going to release

**Comment by ovr** [comment]
Big thanks to @pavellee for PR, and @vitalybaev for problem confirm

> AS I known, Facebook return token as string access_token=XXXXX&expires=XXXX

Sorry guys that I didn't indicate problem earlier and didn't think that Facebook can broke OAuth
Next time, I will test it and I am going to write functionality tests (that can help us to indicate problems)

BTW, Released `1.2.1` ;)

**Pull request closed without merging**
