### PR TITLE
Avoid "Undefined property" error if picture is not fetched.

### PR DESCRIPTION
**Pull request by ADmad**
I created a new `1.x` branch as I couln't find any other appropriate branch for fixes to 1.x series.

### CODE REVIEW

**Comment by ADmad** [comment]
@ovr Ping

**Comment by ovr** [comment]
Thank you @ADmad !

**Comment by ovr** [comment]
Prepared release:

https://github.com/SocialConnect/auth/releases/tag/1.13.1
https://github.com/SocialConnect/auth/releases/tag/2.1.1

**Comment by ADmad** [comment]
I was hoping for #79 to be merged too before a new 1.x release :)

**Pull request merged**
