### PR TITLE
Handle case when Facebook user denies access.

### PR DESCRIPTION
**Pull request by ADmad**
Hey!

Type: bug fix

Link to issue: #54

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/SocialConnect/auth/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I wrote some tests for this PR.

Thanks :smiley_cat:

### CODE REVIEW

**Comment by ovr** [comment]
Thank you 👍 🍺 🐻

**Comment by ADmad** [comment]
No problem, awaiting new release with this fix :smile:

**Comment by ovr** [comment]
@ADmad `1.4.0` Released, can you try it? Thank

**Comment by ADmad** [comment]
Yup, works as expected :+1:

**Pull request closed without merging**
