### PR TITLE
Add Google::getScopeInline().

### PR DESCRIPTION
**Pull request by ADmad**
Hey!

Type: enhancement

Link to issue:

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/SocialConnect/auth/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

This allows specifying each scope as a separate array value in config
instead of an array with single space separated string.

Thanks :smiley_cat:

### CODE REVIEW

**Comment by ovr** [comment]
Restarting tests

**Comment by ADmad** [comment]
Any particular reason you have used `--prefer-source` instead of `--prefer-dist` for `composer install` in `travis.yml`?  It's slows down the build considerably :)

**Comment by ADmad** [comment]
Ping, I think this is good to merge :)

**Comment by ovr** [comment]
My macbook is broken (waiting from service center). I will try to find another pc today to merge it and test.

**Comment by ADmad** [comment]
Sounds like 1st world problem :)

**Comment by ovr** [comment]
I am sorry for delay. Still w8ting for my macbook :( They promise that I will get it tomorrow...
Life without macbook is not a life :(

**Comment by ovr** [comment]
LGTM, Thank you for patch, you are welcome!
🍻

**Pull request merged**
