### PR TITLE
Update GitLab API Version from 3 to 4

### PR DESCRIPTION
**Pull request by makkus183**
Hey!

Type: bug fix

Link to issue: #157 

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [Contributing Guidelines](https://github.com/SocialConnect/auth/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

Update of API Version, see #157 

Thanks :smiley_cat:

### CODE REVIEW

**Comment by ADmad** [comment]
@ovr Would you mind doing a new release please? We have a couple of providers updated and a new one added since the last release.

**Comment by ovr** [comment]
@ADmad I thought that I changed permissions that you are allowed to do that. can you verify it? Thanks

**Comment by ADmad** [comment]
@ovr I do have the perms. With a new provider added do you prefer a new minor?

**Comment by ADmad** [comment]
3.3.0 released.

**Pull request merged**
