### PR TITLE
Bump up phpstan checks to level 4.

### PR DESCRIPTION
**Pull request by ADmad**
Hey!

Type: code quality

For all OAuth1 providers error as below is shown for `getIdentity()` method:
```
Property SocialConnect\OAuth1\AbstractProvider::$consumerToken (SocialConnect\OAuth1\Token) does not accept SocialConnect\Provider\AccessTokenInterface.
```

for statement

```
$this->consumerToken = $accessToken;
```

That's a valid error since `SocialConnect\OAuth1\AbstractProvider::$consumerToken` property is supposed to be an `SocialAuth\OAuth1\Token` instance which does not extend the `AccessTokenInterface`.

I leave it to you to do the needful to fix it :slightly_smiling_face:.

### CODE REVIEW

**Comment by ovr** [comment]
Hey!

Looks like, Gitlab CI not working with PRs from another repositories
Need to verify...

**Comment by ovr** [comment]
Re-trigger by close-open didnt help...

**Comment by ovr** [comment]
Imho: 

https://gitlab.com/gitlab-org/gitlab-ee/issues/13065#note_199779166

**Comment by ADmad** [comment]
Add job for phpstan check on Travis :slightly_smiling_face:.

**Comment by ADmad** [comment]
https://travis-ci.org/SocialConnect/auth/jobs/567305693

**Comment by ovr** [comment]
FYI: https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/15082

MR landed: "Run pipelines for GitHub pull requests"

Target 12.2 that will be released in 5 days, will be cool if this will be merged
We will be able continue to use GitLab CI and probably drop TravisCI

😄

**Pull request closed without merging**
